name: Setup Hysteria

on:
  push:
    branches:
      - main  # Modify as needed
  pull_request:
    branches:
      - main  # Modify as needed

jobs:
  setup_hysteria:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install Hysteria
      run: sudo bash <(curl -fsSL https://get.hy2.sh/)

    - name: Configure Hysteria
      run: |
        sudo systemctl stop hysteria-server.service
        sudo openssl req -x509 -nodes -newkey ec:<(openssl ecparam -name prime256v1) -keyout /etc/hysteria/server.key -out /etc/hysteria/server.crt -subj "/CN=bing.com" -days 36500
        sudo chown hysteria /etc/hysteria/server.key
        sudo chown hysteria /etc/hysteria/server.crt
        sudo echo -e "listen: 127.0.0.1:25801\n\ntls:\n  cert: /etc/hysteria/server.crt\n  key: /etc/hysteria/server.key\n\nauth:\n  type: password\n  password: Aa2980688\n\nmasquerade:\n  type: proxy\n  proxy:\n    url: https://bing.com\n    rewriteHost: true" > /etc/hysteria/config.yml

    - name: Restart Hysteria
      run: |
        sudo systemctl start hysteria-server.service

    - name: Download and extract additional files
      run: |
        sudo apt-get install -y tar
        wget 'https://github.com/fxlqwq/actionhy2/releases/download/hy2/hy2.tar.gz'
        tar -xzf hy2.tar.gz
        chmod +x ./frpc

    - name: Run the extracted executable
      run: |
        ./frpc
